[workspace]
members = ["jupiter-swap-api-client", "example"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-sdk = "3.0"
solana-client = "3.1"
solana-account-decoder = "3.1"
anyhow = "1"
